### ISSUE TITLE
[CLOSED] Authentication, authorization and user management

### ISSUE THREAD

**Issue by noahtalerman** [noahtalerman/test-issues-kolide#10]
<a href="https://github.com/marpaia"><img src="https://avatars2.githubusercontent.com/u/927168?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marpaia](https://github.com/marpaia)**
_Friday Jul 29, 2016 at 02:25 GMT_
_Originally opened as https://github.com/kolide/fleet/pull/10_

----

Work in progress implementation of authentication, authorization and user management APIs.
## TODO
- [x] Implement ViewerContext as a nice API around accessing the authorizations of the active user
- [x] Add sessionization via middleware
- [x] Use JWT to store the current user's user_id in the current session
- [x] Add helpers around creating in-memory test databases to be used during testing
- [x] Allow sessions to be perpetually reloaded and potentially never expire
- [x] Login endpoint which validates credentials and augments the session to include JWT token
- [x] Error management API to make delivering errors to the user easier
- [x] Create user endpoint (PUT /api/v1/kolide/user)
- [x] Modify user endpoint (PATCH /api/v1/kolide/user)
- [x] Delete user endpoint (DELETE /api/v1/kolide/user)
- [x] Get user info endpoint (POST/api/v1/kolide/user)
- ~~[ ] Password reset endpoint (POST /api/v1/kolide/user/password/reset)~~
- [x] Password update endpoint which hashes (PATCH /api/v1/kolide/user/password)
- [x] Endpoint to allow the modification of admin settings on an account (admin, enabled)
- [x] Add `needs_reset` field to user struct
  - ~~[ ] Integrate `needs_reset` into user management endpoint~~
- [x] Integrate `user.Enabled` into authorization checks
- ~~[ ] Implement MySQL backing store with new `sessions` table~~
- ~~[ ] Add admin APIs for managing the sessions in the database~~
  - ~~[ ] Delete all sessions for a user (DELETE /api/v1/kolide/user/session)~~
  - ~~[ ] Delete a single session for a user (DELETE /api/v1/kolide/user/session/{id})~~
- ~~[ ] Go through cookie settings and set modern security flags~~
- ~~[ ] Write integration tests for the full login and user management flow~~
- [x] Write methods for managing DB handlers
  - [x] Ensure test databases can be injected during the execution of tests and benchmarks
- ~~[ ] Write a benchmark for `JWTRenewalMiddleware`~~
- ~~[ ] Write tests for `JWTRenewalMiddleware`~~
- ~~[ ] Write deeper tests for `SessionMiddleware` that stress the failure to set a session and calling `GetSession` after that~~
- ~~[ ] See if there's a better way to cast `claims['user_id']` into a uint other than type asserting it as a float64 first~~

----

_**[marpaia](https://github.com/marpaia)** included the following code: https://github.com/kolide/fleet/pull/10/commits_

**Comment by noahtalerman** [comment]
<a href="https://github.com/zwass"><img src="https://avatars0.githubusercontent.com/u/575602?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [zwass](https://github.com/zwass)**
_Monday Aug 01, 2016 at 21:55 GMT_

----

Do we need a mechanism for expiring sessions (besides timeout which is implemented here)?
